### ISSUE TITLE
Autocompletion doesn't work anymore after upgrading git to version 2.20.0

### ISSUE THREAD

**Issue by cippaciong** [thoughtbot/gitsh#336]
Hello, starting from today autocompletion is not working anymore for basic git commands (e.g. `push`, `checkout`, `pull`, etc.), I'm running the latest stable release of `gitsh`.
~~The only possible reason I see for this behaviour is that today I upgraded git from `2.19.2-1` to `2.20.0-1` through regular system updates (Archlinux). Except from that I can't find or remember any other relevant change related to git since yesterday.
Let me know if there is any additional information I can provide~~

**EDIT**: I downgraded git back to version `2.19.2` and I can confirm that the autocompletion issue is happening only with git `2.20.0`

**Comment by georgebrock** [comment]
@cippaciong Thanks for the report.

It looks like the way we're getting a list of Git commands no longer works. We parse `git help -a`, which is the way the official `git-completion.sh` script used to handle things before https://github.com/git/git/commit/6bb2dc0b9472a84c7d17ee93bda28a7c1c97d415 introduced a much better approach with `git --list-cmds`.

The format of `git help -a` has subsequently changed, so our parsing code no longer works. We should either update the parsing code, or switch to using `--list-cmds`.

Unfortunately the git(1) manual page says that `--list-cmds` …

> is an internal/experimental option and may change or be removed in the future.

Whatever approach we take here, the `Gitsh::GitRepository#commands` method will need updating, and will probably need to support multiple Git versions.

**Comment by georgebrock** [comment]
Thanks for trying that out. The output I see on 2.20.0 from `git help -a` has command descriptions, which could be mistaken as other commands if we just change the regexp, e.g.

```
Main Porcelain Commands
   add                  Add file contents to the index
   am                   Apply a series of patches from a mailbox
   …
```

I worry this might correctly tab-complete `add` and `am`, but also incorrectly tab complete `Apply`, `file`, `contents`, etc.

We already have some version-dependent code in this class (e.g. `#available_config_variables` tries two techniques depending on the Git version), so I wonder if making this try something like `git --list-cmds` then fall back to a modern `git help -a` approach, and finally the older `git help -a` approach would be the most robust thing.

**Comment by cippaciong** [comment]
> The output I see on 2.20.0 from git help -a has command descriptions

You're right! I don't know how I failed to notice command descriptions :sweat_smile: and indeed they are incorrectly added to tab-completion.

**Comment by georgebrock** [comment]
> I don't know how I failed to notice command descriptions

I failed to notice this entire bug, so I think you're still ahead on noticing things 😉

**Comment by georgebrock** [comment]
I talked this through with some folk at thoughtbot who had various Git versions installed, and we discovered that `git help -a --no-verbose` outputs the old `help -a` format on recent Git versions, but is an error on older Git versions.

Seems like the right approach is:

1. Try `git --list-cmds`
2. Fall back to `git help -a --no-verbose` expecting the old format
3. Fall back to `git help -a` expecting the old format

https://github.com/git/git/commit/26c7d0678324d99b56d3044acfdfab57ee670af4 is where `--no-verbose` is introduced.

Thanks @edwardloveall, @iwz, @mike-burns, and @sharplet !

**Comment by iwz** [comment]
I'm now running git 2.20. thanks for prompting me to upgrade, @georgebrock :)

**Comment by georgebrock** [comment]
@iwz But now gitsh won't work! 😱

**Comment by georgebrock** [comment]
Fix in progress: #337

**Comment by georgebrock** [comment]
I've merged #337, this will be in the next release which I'll try to get out as soon as possible.

**Comment by cippaciong** [comment]
Thanks for fixing and for the new release :slightly_smiling_face:

**Comment by georgebrock** [comment]
@cippaciong Thanks for the bug report!

**Comment by joshukraine** [comment]
@georgebrock I'm using git v2.20.1 with gitsh v0.13. But tab completion in gitsh is still broken for me. My understanding from reading this issue is that the fix was done in PR #337 and that it was included in the latest release (v0.13). Is that correct? Is there something I need to do locally to get tab completion working again? Thanks!

**Comment by joshukraine** [comment]
@georgebrock Poked around a bit more and realized that my problem is more specific. Tab completion of git commands _does_ seem to be working. What appears broken for me is the completion of file paths when using git _aliases_. So for example, I have `a` aliased to `add` in my gitconfig file. With previous versions of gitsh, if I wanted to add a modified file to the staging area, I would do something like `a source/asset<tab>` and that would complete the path. Same with `co` aliased to `checkout`. To tab complete checking out a feature branch I could do `co new-feat<tab>` and it would try to complete the branch. These work if I use the full git command (e.g. `checkout ...`) but not with aliases.

Sorry for the long explanation. Any suggestions? Thanks! 🙂

**Comment by georgebrock** [comment]
@joshukraine Thanks for the additional detail.

I think the issue you're seeing (arguments not completing for aliases) is different for the one reported here (commands not completing with Git 2.20), so I'm going to open a new issue.
